### ISSUE TITLE
健康打卡没打上

### ISSUE THREAD

**Issue by pyh4** [Freedomisgood/When_Coding_in_ZJU#1]
```shell
# python3 health_checkin_helper_cst.py
欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com
训练数据支持来源于:http://146.56.204.113:19199/preview
爬虫框架feapder可快速一键接入，快速开启爬虫之旅：https://github.com/Boris-code/feapder
正在为XXXXXXXX健康打卡
统一认证平台登录成功~
[注意] 未提供token，不进行pushplus推送！
```

**Comment by Freedomisgood** [comment]
> ```shell
> # python3 health_checkin_helper_cst.py
> 欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com
> 训练数据支持来源于:http://146.56.204.113:19199/preview
> 爬虫框架feapder可快速一键接入，快速开启爬虫之旅：https://github.com/Boris-code/feapder
> 正在为XXXXXXXX健康打卡
> 统一认证平台登录成功~
> [注意] 未提供token，不进行pushplus推送！
> ```


应该是账号密码输入错误，现已修复。
此外，建议使用：[Zju_health_checkin_helper](https://github.com/Freedomisgood/Zju_health_checkin_helper)，本仓库比较冗余，后期不再准备额外维护打卡
